In [11]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
x = 3*a**3
x

tensor([24., 81.], grad_fn=<MulBackward0>)

In [12]:
y = b**2
y

tensor([36., 16.], grad_fn=<PowBackward0>)

In [13]:
Q = 3*a**3 - b**2
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [14]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

C:\Users\linho\AppData\Local\Temp\ipykernel_16844\2443113738.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  Q.grad


In [15]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [16]:
a.grad

tensor([36., 81.])

In [17]:
b.grad

tensor([-12.,  -8.])